pipeline {
    agent any

    tools {
        maven 'Maven 3.9.9'
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn clean install -DskipTests'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Report') {
            steps {
                sh 'echo generate test'
            }
            post {
                always {
                    allure includeProperties: false, results: [[path: 'target/allure-results']]
                }
            }
        }
    }
}