//pipeline {
//    agent any
//    tools {
//        jdk 'JAVA_HOME'
//        maven 'MAVEN'
//    }
//    stages {
//        stage("Clone") {
//            steps {
//                script {
//                    checkout scm
//                    sh "git fech"
//                    sh "git checkout main"
//                    sh "git pull origin main"
//                }
//            }
//            stage("Build") {
//                steps {
//                    sh "mvn install -DskipTests"
//                }
//            }
//            stage("Run Tests"){
//                steps{
//                    sh "mvn test"
//                }
//            }
//        }
//    }
//}

pipeline {
    agent {
        docker { image 'openjdk:21-jdk' }
    }

    stages {
        stage('Clone') {
            steps {
                sh 'echo Clonando projeto...'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean install -DskipTests' // ou o comando de build desejado
            }
        }
        stage('Run Tests') {
            steps {
                sh 'mvn test'
            }
        }
    }
}
